/* eslint-disable @next/next/no-page-custom-font */
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* verificar */}
        {/* https://www.devmedia.com.br/html-meta-tags-entendendo-o-uso-de-meta-tags/30328 */}
        <meta httpEquiv="content-language" content="pt-br, en-US, fr" />
        <meta httpEquiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="copyright" content="© 2023 Felipe Scherer" />
        <meta name="rating" content="general" />
        {/* <meta httpEquiv="refresh" content="3;url=https://www.mozilla.org" /> */}

        <link
          href="https://fonts.googleapis.com/css2?family=Darker+Grotesque:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />

        <link
          rel="preconnect"
          href="https://user-images.githubusercontent.com"
        />
        <link
          rel="dns-prefetch"
          href="https://user-images.githubusercontent.com"
        />

        <meta
          name="theme-color"
          media="(prefers-color-scheme: light)"
          content="cyan"
        />
        <meta
          name="theme-color"
          media="(prefers-color-scheme: dark)"
          content="black"
        />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  )
}
